export const APP_CHECKIN = 'APP_CHECKIN'
export const APP_CHECKOUT = 'APP_CHECKOUT'


export const JSON_FEED_FETCHING = 'JSON_FEED_FETCHING';
export const JSON_FEED_SUCCESS = 'JSON_FEED_SUCCESS';
export const JSON_FEED_FAILED = 'JSON_FEED_FAILED';